<template>
    <div>
        <div></div>
        <div></div>
        <div></div>
    </div>
</template>
<style>
    *{
        margin:0;
        padding:0;
        background-color:red;
    }
    div{
        float:left;
        width:100px;
        height:100px;
        background-color: aqua;
        margin-bottom:20px;
    }
</style>
